### ISSUE TITLE
FADU over-counts specific genes

### ISSUE THREAD

**Issue by matt-chung** [IGS/FADU#2]
I simulated an E. coli data set and compared the performance of FADU against other quantification tools/modes. This situation happens quite a bit in which FADU has way more counts than all the other tools.

In the case of gene-b0202, the simulated data set should have count of 278. However, FADU obtains counts of ~3400. Here are the counts derived from other tools also:

```
> print(counts[[i]]["gene-b0202",])
fadu_default express_default express_optimized featurecounts_default featurecounts_overlap featurecounts_fractionaloverlap htseq_union
gene-b0202      3419.68        192.7041          206.0669                     0                     0                              NA           0
           htseq_intersectionstrict htseq_intersectionnonempty htseq_unionnonuniqueall kallisto_default salmon_default salmon_optimized
gene-b0202                        0                          0                       0          234.333        233.665          234.283
```

When I look at the BAM files to look at the alignments over the area of gene-b0202, I can see that FADU obtains more counts (3,419) than there are actual alignments (1,869) for gene-b0202:

```
$ samtools view sample_01.sortedbyposition.bam NC_000913.3:225381-225457 | wc -l
1869
```

Here's the command I used to run FADU:
```
julia ./fadu.jl -b ./sample_01.sortedbyposition.bam -g ./GCF_000005845.2_ASM584v2_genomic.gff -o ./fadu_default -s yes -f gene -a ID
```

**Comment by adkinsrs** [comment]
Committed a fix.  There were a couple of issues.

1) The sum of all feature counts for features overlapping a multmapped alignment record was incorrect as the total counts for every feature were being counted instead of just those overlapping the record. This was resulting in inflated feature counts for those features, as well as a lower TPM value in the final output
2) Feature counts for genes that overlap one or more multimapped alignment record were being further inflated because the adjustment to counts was being on the features' total overlap feature counts instead of just the count for the multimapped alignment overlap currently being processed.
